deployment:
  replicas: 2
  image:
    repository: "wso2/wso2websubhub"
    pullPolicy: IfNotPresent
    tag: "1.0.0-M1-RC4"
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  config:
    server:
      port: 9000
      id: "websubhub-1"
    state:
      snapshot:
        url: "http://websubhub-consolidator-service:10001/consolidator/state-snapshot"
      events:
        topic: "websub-events"
        consumerIdPrefix: "websub-events-consumer"
    store:
      solace:
        url: "tcp://solace-pubsubplus-dev:55555"
        messageVpn: "default"
        auth:
          username: "admin"
          password: "password"
        consumer:
          receiveTimeout: "10.0"
        admin:
          url: "http://solace-pubsubplus-dev:8080/SEMP/v2/config"
          timeout: "30.0"
          auth:
            username: "admin"
            password: "password"
    delivery:
      timeout: "60.0"
      retry:
        count: 3
        interval: "3.0"
        backOffFactor: "2.0"
        maxWaitInterval: "20.0"
        statusCodes: [500, 502, 503]
    logging:
      level: "INFO"
