deployment:
  replicas: 1
  image:
    repository: "wso2/websubhub"
    pullPolicy: IfNotPresent
    tag: 1.0.0-M1-RC3
  resources:
    requests:
      cpu: "1"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
  config:
    server:
      port: 9000
      id: "websubhub-1"
    state:
      snapshot:
        url: "http://localhost:10001"
      events:
        topic: "websub-events"
        consumerIdPrefix: "websub-events-consumer"
    store:
      solace:
        url: "tcp://localhost:55554"
        messageVpn: "default"
        auth:
          username: "admin"
          password: "admin"
        consumer:
          receiveTimeout: "10.0"
        admin:
          url: "http://localhost:8080/SEMP/v2/config"
          timeout: "30.0"
          auth:
            username: "admin"
            password: "admin"
    delivery:
      timeout: "60.0"
      retry:
        count: 3
        interval: "3.0"
        backOffFactor: "2.0"
        maxWaitInterval: "20.0"
        statusCodes: [500, 502, 503]
    logging:
      level: "INFO"

# ingress:
#   hosts:
#     - host: wso2-websubhub.local
#       paths:
#         - path: /hub
#           pathType: Prefix
#   tls: []
