deployment:
  replicas: 1
  image:
    repository: "wso2/websubhub"
    pullPolicy: IfNotPresent
    tag: 1.0.0-M1
  config:


ingress:
  hosts:
    - host: wso2-websubhub.local
      paths:
        - path: /hub
          pathType: Prefix
  tls: []
